# Generated by Django 5.2.4 on 2025-07-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_emailotp_created_at_alter_emailotp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
