# Generated by Django 5.2.4 on 2025-08-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_order_orderitem_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_type', models.CharField(choices=[('retail', 'Retail Purchase'), ('wholesale', 'Wholesale Purchase')], default='retail', max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('product_interest', models.CharField(blank=True, choices=[('raw-cashews', 'Raw Cashews'), ('roasted-cashews', 'Roasted Cashews'), ('flavored-cashews', 'Flavored Cashews'), ('cashew-nuts', 'Premium Cashew Nuts'), ('bulk-cashews', 'Bulk Cashews'), ('other', 'Other')], max_length=50)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
