# Generated by Django 5.2.4 on 2025-08-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_enquiryform'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
